//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace himchistka.practic.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientDiscounts
    {
        public int ClientDiscountID { get; set; }
        public int ClientID { get; set; }
        public int DiscountID { get; set; }
        public Nullable<System.DateTime> AssignedDate { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Discounts Discounts { get; set; }
    }
}
