//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace himchistka.practic.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipment()
        {
            this.MaintenanceLog = new HashSet<MaintenanceLog>();
        }
    
        public int EquipmentID { get; set; }
        public string EquipmentName { get; set; }
        public int BranchID { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public decimal PurchasePrice { get; set; }
        public Nullable<System.DateTime> LastMaintenance { get; set; }
        public string Status { get; set; }
        public string SerialNumber { get; set; }
    
        public virtual Branches Branches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaintenanceLog> MaintenanceLog { get; set; }
    }
}
