//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace himchistka.practic.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaintenanceLog
    {
        public int LogID { get; set; }
        public int EquipmentID { get; set; }
        public System.DateTime MaintenanceDate { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public string PerformedBy { get; set; }
    
        public virtual Equipment Equipment { get; set; }
    }
}
