//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace himchistka.practic.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materials
    {
        public int MaterialID { get; set; }
        public string MaterialName { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> StockQuantity { get; set; }
        public Nullable<decimal> MinStock { get; set; }
        public decimal PricePerUnit { get; set; }
        public Nullable<System.DateTime> LastRestocked { get; set; }
    
        public virtual Suppliers Suppliers { get; set; }
    }
}
