//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace himchistka.practic.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipts
    {
        public int ReceiptID { get; set; }
        public string ReceiptNumber { get; set; }
        public int OrderID { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public decimal Amount { get; set; }
        public string PaymentMethod { get; set; }
        public Nullable<int> CashierID { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
